Add open_url function in util.io and its test in test_util.io
cogent3/cogent3 pull request #1065
Opened 2022-06-27 19:21 UTC by Nick-Foto

2022-06-27 23:23 UTC, GavinHuttley requested changes
Thanks for the contribution! The tests are failing due to binary mode revealing platform-specific line endings. Easily addressed (see my suggested patch in the comment) along with the simplification of the tests.

2022-06-27 23:23 UTC, GavinHuttley commented on tests/test_util/test_io.py
> +    def test_open_url(self):
There is a pattern in these tests that can be exploited to reduce the number of lines. Given the root for remote and local files and the different file modes you could simplify these tests, e.g.
```python
local_root = pathlib.Path("data")
remote_root = pathlib.Path("raw.githubusercontent.com/cogent3/cogent3/develop/tests/data")
for file_name in ("c_elegans_WS199_dna_shortened.fasta", "ff2_test.gff"):  # extend for any others
    for mode in ("r", "rb", "rt"):  # extend for any others
        with open_(local_root / file_name, mode=mode) as infile:
            local_data  = infile.read()
        with open_url(f"https://{remote_root / file_name}", mode=mode) as infile:
            remote_data = infile.read()
        # differences in line-endings between platforms mean the binary data may be different
        # You can handle this by splitting the lines so those different characters are removed, thus...
        self.assertEqual(remote_data.splitlines(), local_data.splitlines()) # should work
```

2022-06-28 04:54 UTC, Nick-Foto commented on tests/test_util/test_io.py
> +    def test_open_url(self):
I pushed new changes. Please review and merge these changes.

2022-06-28 08:50 UTC, Nick-Foto commented on tests/test_util/test_io.py
> +    def test_open_url(self):
About new problem in the CI, I installed Python3.7 in my laptop and checked. It works in my laptop with Python 3.7.13.  
After searching about it, I think it is a bug in Python 3.7 [socket module calls with long host names can fail with idna codec error.](https://bugs.python.org/issue32958)

2022-06-28 23:15 UTC, GavinHuttley commented on tests/test_util/test_io.py
> +    def test_open_url(self):
I've reproduced the error and can confirm it is due to using `pathlib.Path()`. If you [look at the traceback](https://github.com/cogent3/cogent3/runs/7086100449?check_suite_focus=true#step:5:139) you'll see the url passed to Python's code is `'raw.githubusercontent.com\\cogent3\[etc...]`.

This is an artefact of `str(pathlib.Path())`. On windows this will convert `raw.githubusercontent.com/cogent3` to what is in the above. So I suggest change the `remote_root` (leave `local_root` unchanged) to a template string.

```python
remote_root = "https://raw.githubusercontent.com/cogent3/cogent3/develop/tests/data/{}" 
```
And use it as
```python
with open_url(remote_root.format(file_name)) as infile:
    remote_data = infile.read()
```

2022-06-28 23:37 UTC, GavinHuttley commented
You can ignore the issues identified by lgtm-com since that's a bug (which I have reported) on their end.

2022-06-29 01:16 UTC, Nick-Foto commented on tests/test_util/test_io.py
> +    def test_open_url(self):
I pushed new changes. Please review and merge these changes.

2022-06-29 01:46 UTC, merged