TST: add test for make_dna_scoring_dict()
cogent3/cogent3 pull request #1505
Opened 2023-07-05 00:37 UTC by KatherineCaley

2023-07-05 07:56 UTC, GavinHuttley requested changes
add a transition != transversion check

2023-07-05 23:02 UTC, KatherineCaley commented
> add a transition != transversion check

I pushed one to my fork yesterday, but is hasn't been automatically be added to the PR? 

@GavinHuttley  I could cancel and reopen the PR?

2023-07-05 23:07 UTC, GavinHuttley commented
> > add a transition != transversion check
> 
> I pushed one to my fork yesterday, but is hasn't been automatically be added to the PR?
> 
> @GavinHuttley I could cancel and reopen the PR?

that is super odd. Yes to close and re-open. 

Actually, here's a better way than checking ts != tv. You explicitly define the values of match, ts and tv in constructing the scoring matrix. Just add those specific values to each tested condition.

2023-07-05 23:18 UTC, KatherineCaley commented
> 
Done. Also pushing up that change appears to have bundled up the rest of them.

2023-07-05 23:47 UTC, GavinHuttley requested changes
In reviewing this, I realise we need better documentation about the assumptions being made by the built-in apps!
So the major change (which is pretty small) is related to that.

2023-07-05 23:47 UTC, GavinHuttley commented on src/cogent3/app/align.py
> +        score_matrix=None,
add type hints on the arguments

2023-07-05 23:47 UTC, GavinHuttley commented on src/cogent3/app/align.py
> +        self.insertion_penalty = insertion_penalty
make all the class attributes semi-private, to discourage the user from messing with them on an instance. The reason this matters is the serialisation of the instance uses `self._init_vals` which is defined on build, so any modification by the user makes the state inconsistent.

2023-07-05 23:47 UTC, GavinHuttley commented on src/cogent3/app/align.py
> +    def main(self, seq1: SeqType, seq2: SeqType) -> AlignedSeqsType:
this won't work with the standard app approach, a single argument is required. Change to
```python
def main(self, seqs: UnalignedSeqsType) -> AlignedSeqsType:
      if seqs.num_seqs > 2:
        return NotCompleted("ERROR", ..., message="maximum number of two seqs per collection", ...)
     seq1, seq2 = seqs.seqs
   ```

2023-07-05 23:47 UTC, GavinHuttley commented on tests/test_app/test_align.py
> +    got = aligner(seqs.get_seq("Human"), seqs.get_seq("Bandicoot"))
change test to using a sequence collection. Add a new test for calling with a sequence collection that does not have 2 sequences.

2023-07-13 11:39 UTC, GavinHuttley approved these changes
Two small changes, which I'll just do. But adding to this review so you see them. Thanks for finishing!

2023-07-13 11:39 UTC, GavinHuttley commented on tests/test_app/test_align.py
> +    print(got)
delete print statement

2023-07-13 11:39 UTC, GavinHuttley commented on tests/test_app/test_align.py
> +    test_moltypes = ["text", "rna", "protein", "protein_with_stop", "bytes", "ab"]
@pytest.mark.paramtrize!!

2023-07-13 11:40 UTC, merged