Add test for querying for non-existent parent/child
cogent3/cogent3 pull request #1530
Opened 2023-07-11 06:29 UTC by KatherineCaley

2023-07-12 01:11 UTC, GavinHuttley requested changes
nice!

1. Suggesting a slight change to code to make it less indented (and thus more readable).
2. In your tests, use an ID that's very clearly not in the db, like `"this id does not exist"`. Makes it clear the ID cannot exist, whereas how do I know the ones you created don't exist, maybe they do and the test passes because of a different error.

2023-07-12 01:11 UTC, GavinHuttley commented on src/cogent3/core/annotation_db.py
> +                if result["parent_id"]:
I suggest a slight change to make the code easier to read
```python
if not result["parentid"]:
    return

# de-indent the remaining code
```

2023-07-12 01:26 UTC, KatherineCaley commented
> 2. In your tests, use an ID that's very clearly not in the db, like `"this id does not exist"`. Makes it clear the ID cannot exist, whereas how do I know the ones you created don't exist, maybe they do and the test passes because of a different error.

@GavinHuttley I chose IDs that do exist in the file! They just do not have a parent or a child. I think using an ID that does not exist in the file would be a different test.

2023-07-13 11:28 UTC, GavinHuttley approved these changes
Noice!

2023-07-13 11:29 UTC, merged