Docstring examples for app.sample.concat and omit_degenerates.
cogent3/cogent3 pull request #1695
Opened 2024-01-15 04:20 UTC by fredjaya

Related to #1636.

Not too sure about lines 67-68 here, as the order of dict items change across `pytest --doctest-module` runs`concatenated.to_dict()`

2024-01-15 05:02 UTC, GavinHuttley requested changes
Thanks @fredjaya !
few thoughts on how to display a representation of an alignment in the docs. Also, I just realised that many apps have a moltype argument, which if set then means the sequence collection / alignment does not have to have had a moltype explicitly set.

Also, all such objects always have a moltype, it's just a default one (like text/ascii or bytes) and we require DNA/RNA/PROTEIN

2024-01-15 05:02 UTC, GavinHuttley commented on src/cogent3/app/sample.py
> +        Alignments without a moltype returns a NotCompleted
same as above regarding defining moltype to app.

2024-01-15 21:01 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Sequences with no matching names returns a NotCompleted (see
Would it be better to define the moltype in the sequence collection, app, or both?

2024-01-16 03:38 UTC, GavinHuttley commented on src/cogent3/app/sample.py
> +        Sequences with no matching names returns a NotCompleted (see
better in the `app`

2024-01-16 10:04 UTC, GavinHuttley approved these changes
Awesome @fredjaya !

2024-01-16 10:04 UTC, merged