DEV: added seqid arg to SeqView, fixes #1708
cogent3/cogent3 pull request #1709
Opened 2024-02-07 23:39 UTC by KatherineCaley

2024-02-07 23:49 UTC, GavinHuttley requested changes
small tweak, we want the property for accessing the value

2024-02-07 23:49 UTC, GavinHuttley commented on src/cogent3/core/sequence.py
>      def offset(self) -> int:
add a "read only" seqid property to the `SeqView` class
```python
@property
def seqid(self):
    return self._seqid
```

2024-02-07 23:49 UTC, GavinHuttley commented on tests/test_core/test_sequence.py
> +    assert sv._seqid is None
change all references to the private attribute `_seqid` to the property `.seqid`

2024-02-08 00:06 UTC, KatherineCaley commented
> small tweak, we want the property for accessing the value

Duh! added @GavinHuttley

2024-02-08 00:28 UTC, GavinHuttley requested changes
Can you add a test showing that when the SeqView is sliced, the seqid value is propagated to the new object

2024-02-08 00:38 UTC, KatherineCaley commented
> Can you add a test showing that when the SeqView is sliced, the seqid value is propagated to the new object

yep!

2024-02-08 01:21 UTC, GavinHuttley approved these changes
🎉 thank you!

2024-02-08 01:21 UTC, merged