Feature/issue 1736
cogent3/cogent3 pull request #1751
Opened 2024-03-12 03:24 UTC by yantonglu

Fixed issue#1736, discontinued `cogent3.maths.special.permutations(), cogent3.maths.special.permutations_exact(), cogent3.maths.special.ln_permutations()` and removed corresponding test `test_maths/test_stats/test_special.py::SpecialTests::test_permutations(),test_permutations_errors(),test_permutations_float(),test_permutations_range(),test_permutations_exact(),test_ln_permutations()`

2024-03-13 01:13 UTC, GavinHuttley requested changes
Thanks for the contribution!

When marking a function to be discontinued we limit our changes to applying the decorator and giving the reason (including referring users to a replacement in another project). In other words, we do not actually change our code within the function since we are going to be deleting it.

2024-03-13 01:13 UTC, GavinHuttley commented on src/cogent3/maths/stats/special.py
> +    return log(scipy.special.perm(n, k, exact=False))
The point here is not to replace our function with that from Scipy; rather, just use the decorator as indicated. Revert the change within the function to the original.

2024-03-13 01:13 UTC, GavinHuttley commented on src/cogent3/maths/stats/special.py
> +    return scipy.special.perm(n, k, exact=False)
The point here is not to replace our function with that from Scipy; rather, just use the decorator as indicated. Revert the change within the function to the original.

2024-03-13 01:13 UTC, GavinHuttley commented on src/cogent3/maths/stats/special.py
> +    return scipy.special.perm(n, k, exact=True)
The point here is not to replace our function with that from Scipy; rather, just use the decorator as indicated. Revert the change within the function to the original.

2024-03-13 01:13 UTC, GavinHuttley commented on src/cogent3/maths/stats/special.py
> +import scipy
Delete this import. The point here is not to replace our function with that from Scipy; rather, just use the decorator and tell users where to go to find the replacement.

2024-03-13 01:27 UTC, yantonglu commented
OK, I'll revert them.

2024-03-13 02:14 UTC, yantonglu commented
I have reverted the changes within functions, please review them again. Thanks!

2024-03-20 00:49 UTC, GavinHuttley approved these changes
awesome job @yantonglu , thanks for the contribution!

2024-03-20 00:49 UTC, GavinHuttley commented
fixes #1736

2024-03-20 00:51 UTC, merged