DOC: code example snippet to cogent3.app.sample.omit_duplicated, fixes #1752
cogent3/cogent3 pull request #1765
Opened 2024-03-13 09:37 UTC by Ruizhe-wang

2024-03-13 09:41 UTC, Ruizhe-wang commented
DOC: add code example snippet to cogent3.app.sample.omit_duplicated, fixes #1752

2024-03-13 09:42 UTC, Ruizhe-wang commented
DOC: add code example snippet to cogent3.app.sample.omit_duplicated, fixes https://github.com/cogent3/cogent3/issues/1752

2024-03-14 03:12 UTC, fredjaya commented
Thanks for the contribution!

I have suggested a few improvements for the example descriptions. 

After adding docstring examples, check that they work with `doctest`. A few errors came up regarding the multi-line code missing `...` at the beginning of the lines. Instructions for testing can be found [here](https://github.com/cogent3/c3dev/wiki/How%E2%80%90to-write-docstring-examples-for-methods-and-functions#how-to-test-docstring-examples).

Let me know here if you have any questions at all!

2024-03-14 03:14 UTC, fredjaya requested changes
Thanks for the contribution!

I have suggested a few improvements for the example descriptions. 

After adding docstring examples, check that they work with `doctest`. A few errors came up regarding the multi-line code missing `...` at the beginning of the lines. Instructions for testing can be found [here](https://github.com/cogent3/c3dev/wiki/How%E2%80%90to-write-docstring-examples-for-methods-and-functions#how-to-test-docstring-examples).

Let me know here if you have any questions at all!

2024-03-14 03:14 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Exclude all members of duplicated sets:
Replace with 

```
Create an app to exclude all duplicate sequences from the collection.
```

2024-03-14 03:14 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        "seq1": "ATCG",
Add leading `...`

2024-03-14 09:46 UTC, Ruizhe-wang commented
Hi,
Thank you for your guidance!
I have completed the improvements you suggested. Please let me know if there are any further modifications needed. And I also notice when I commit in Github desktop, an email from Github "CI: Some jobs were not successful", should I worry about it? @fredjaya

2024-03-15 00:06 UTC, fredjaya requested changes
Hi Ruizhe, thanks for the updates, we are nearly there!

`doctest` threw errors with the full stops used, where `·` is a different symbol to `.` 

```python
ord(".") # 46, correct one
ord(".") # 183
```

I have provided snippets for you to copy and paste throughout.

2024-03-15 00:06 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        >>> aln_dna = make_aligned_seqs({
Replace with

```
>>> aln_dna = make_aligned_seqs({
... "seq1": "ATCG", 
... "seq2": "ATYG", 
... "seq3": "GGTA",
... "seq4": "GGTA"
... }, 
... moltype="DNA")
```

2024-03-15 00:09 UTC, fredjaya commented
The GitHub actions haven't been run so it looks like an error, no need to worry.

2024-03-25 22:33 UTC, merged