feature/issue 1754
cogent3/cogent3 pull request #1767
Opened 2024-03-13 12:59 UTC by Lizhaozhe123

Add code example snippet to cogent3.app.sample.trim_stop_codons

2024-03-13 13:08 UTC, Lizhaozhe123 commented
I have figured out #1754

2024-03-14 03:51 UTC, fredjaya requested changes
Thanks for the contribution!

I have added minor suggestions to reduce repetition in the examples, and to further improve the example descriptions and code output (with `.to_pretty()`).

Let me know here if you have any questions!

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Removes trailing stop codons from sequences in a sequence collection or alignment
Add a blank line before the description

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        >>> from cogent3 import make_unaligned_seqs, make_aligned_seqs, get_app
Move this above `>>> ualn =  ...`

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        >>> print(result.to_dict())
Output results with `.to_pretty()` instead of `to_dict()`

```python
>>> print(result.to_pretty())
s1    AAATTTCCC
s2    AAATTT
```

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Create an app to remove stop codons, use different genetic code
You can delete this example, as `gc=1` by default and accounted for in the first example

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Create a sample unaligned sequence data and an app to remove stop codons
Replace `Create a sample unaligned sequence data` with `Create a sample of unaligned sequences`

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Create a sample alignment sequence data
Replace with `Create a sample of unaligned sequences and an app to remove stop codons`

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        >>> app = get_app("trim_stop_codons", gc=1)
A new app doesn't need to be defined here - reuse the one from line 845

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        >>> print(result.to_dict())
Use `to_pretty()`

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        >>> print(result.to_dict())
Use `to_pretty()`

2024-03-14 03:51 UTC, fredjaya commented on src/cogent3/app/sample.py
> +        Create an app to remove stop codons, use different genetic code
Replace `use different genetic code` with 

```
using the genetic code for "Vertebrate Mitochondrial".

For a list of all genetic codes, see (https://cogent3.org/doc/cookbook/what_codes.html).
```

2024-04-05 01:59 UTC, closed without merging

2024-04-05 02:00 UTC, GavinHuttley commented
No response to review requests. But we appreciate the contribution. I will acknowledge your contribution in our changelog, so thank you!