DEP: remove the erf() and erfc function fixes #1778
cogent3/cogent3 pull request #1782
Opened 2024-03-18 03:44 UTC by ShunyiYang

This time, I used GitHub Desktop. Previously, I used the Git command line, but there was a line ending issue: I am on a Windows system, and after downloading cogent3 to my computer, all the files had \r\n line endings instead of \n, which resulted in over a million modifications when compared to the original repository. This problem doesn't occur with GitHub Desktop. However, I still want to know how to solve this issue if using the Git command line.

2024-03-18 05:53 UTC, ShunyiYang commented
Oh, I get it now. After changing the VSCode settings, I need to redownload cogent3 so that VSCode can open files in LF mode.

2024-03-19 21:29 UTC, GavinHuttley requested changes
Thanks so much for the contribution!

One small task left before wrapping up your first time contribution to Cogent3 🚀! Run the linters against the code (see comment on the file).

2024-03-19 21:29 UTC, GavinHuttley commented on src/cogent3/maths/stats/special.py
> +
you should run black and isort against the code. In the root directory for the project
```
$ black .; isort .
```
these ensure formatting, white space etc.. all match the project standards

2024-03-25 22:40 UTC, merged

2024-03-25 22:42 UTC, GavinHuttley commented
fixes #1738