MAINT: refactor sqlite array type handling
cogent3/cogent3 pull request #1794
Opened 2024-03-27 23:44 UTC by GavinHuttley

[CHANGED] make sure BytesIO instances are closed when
    finished.

2024-03-28 04:41 UTC, GavinHuttley commented
codacy issue relates to Markdown formatting that's used by scriv for producing changelog. It's safely ignored.

2024-03-28 05:03 UTC, rmcar17 requested changes
Other than that relatively small comment, looks good to me!

Should we type those functions as well as `array_to_sqlite` and `sqlite_to_array` while we're at it? Didn't think about it in my initial implementation.

2024-03-28 05:05 UTC, rmcar17 commented
The pull request reminds me I should detail the solution in the issue (#1776) linked to by the warning.

2024-03-29 03:38 UTC, GavinHuttley commented on tests/test_core/test_annotation_db.py
> +    with io.BytesIO(data) as data:
I agree we need to add type hints. I have also taken your suggestion of renaming the variables in the test function.

2024-03-29 03:42 UTC, rmcar17 approved these changes
Looks good to me!

2024-03-29 03:45 UTC, merged