Plugin support
cogent3/cogent3 pull request #1818
Opened 2024-04-21 23:10 UTC by khiron

Adds plugin-support features to develop branch
- implementation of stevedore library to replace `_app_registry`
- migration of internal apps from automatic registry with `_app_registry` to registration though entry-points registered to the group `cogent3.app`
- conversion of app tests to use the plugin infrastructure 
  - deprecation of tests that dynamically load apps
  - separation of tests that probe composability (into `test_composable.py`) and tests that probe plugin functionality (into `test_plugins.py`)

2024-04-24 11:39 UTC, GavinHuttley requested changes
few small changes, plus whatever we raised in the CZI meeting.

fantastic progress!

2024-04-24 11:39 UTC, GavinHuttley commented on requirements.txt
> +stevedore
pin the version in here, it lets dependabot trigger PRs when stevedore is updated

2024-04-24 11:39 UTC, GavinHuttley commented on tests/test_app/test_plugins.py
> +def test_apps_can_be_deprecated(mock_extension_manager):
we're deleting this attribute, so remove the tests

2024-04-24 11:39 UTC, GavinHuttley commented on tests/test_app/test_plugins.py
> +    assert (
tests of exact string values are fragile, look for certain words. Edit the test to do this.

2024-04-24 11:39 UTC, GavinHuttley commented on src/cogent3/app/__init__.py
> +# exclude apps from deprecated modules
delete all uses of the `__deprecated` variable. We don't need this anymore.

2024-04-26 05:06 UTC, khiron reviewed
following on from my review during the 23/4 CZI meeting.  All items have been  resolved

2024-04-27 02:53 UTC, GavinHuttley approved these changes
🎉 awesome, ready to merge. You get the privilege of pressing that button 🥳

2024-04-27 02:58 UTC, merged