Start on SequenceCollections refactor
cogent3/cogent3 pull request #1881
Opened 2024-05-30 05:31 UTC by KatherineCaley

working towards #1867

2024-05-30 05:34 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
line 213 changes `.seq` from a `SeqData` instance, to a `str`. My instinct is that it should be a new `SeqData` instance where the seq corresponding to `seqid` is sliced

2024-05-30 05:38 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
> +    data
let's decide what forms of `data` we are going to support being passed to `make_unaligned_seqs`. currently I am supporting: 
- `dict{name: seq, ...}`
- `[[name, seq]...]` (lists or sets) 
- `[seq, ...]` (lists or sets) 
- `2D numpy array`
which of these are actually necessary and which have I missed?

2024-05-30 05:40 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
> +
naming consistency (using `validate_names`) is currently the responsibility of `SeqData` but I think it should be moved into the `SequenceCollection`

2024-05-30 05:42 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
> +    data
Should we support creating a `SequenceCollection` where data is already a `SeqData` instance?

2024-05-30 09:14 UTC, GavinHuttley requested changes
Great progress!
I'm going to get all radical here and suggest that we rename `SeqData` to `SeqsData` because it can contain many sequences.
I also need to update the testing code so that it uses the new versions that I just pushed in for molecular type, alphabets and sequence.

2024-05-30 09:14 UTC, GavinHuttley commented on tests/test_core/test_new_alignment.py
>      seq_index,
Change all imports to use the new versions of the MolType sequence and alphabet modules.

2024-05-30 09:14 UTC, GavinHuttley commented on src/cogent3/core/new_alignment.py
> +    def __init__(self, seq_data: SeqData, moltype: MolType):
We should require these to be keyword arguments. So `(self, *, ...)`

2024-05-31 03:25 UTC, GavinHuttley requested changes
Great progress, and some good issues raised. A few small comments to address small comments to address.

2024-05-31 06:04 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
> +        return self.__class__(
@GavinHuttley can you dumb it down to me what you mean by "just return self" - is it in the context of supporting sliced, or to replace the current code?

2024-05-31 06:08 UTC, GavinHuttley commented on src/cogent3/core/new_alignment.py
> +        return self.__class__(
Sorry, too brief a comment! I meant the following
```python
def copy(self):
    return self
```

2024-06-03 02:17 UTC, merged