ENH: add reversed field to SeqsData
cogent3/cogent3 pull request #1926
Opened 2024-06-26 04:43 UTC by KatherineCaley

2024-06-26 07:19 UTC, GavinHuttley requested changes
few comments for your brain and small code tweak

2024-06-26 10:59 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
> +        step = -1 if self._reversed_seqs.get(seqid, False) else 1
I don't think that this will work if we are supporting multiple calls of `rc()`, which can lead to seqids corresponding to `True`

2024-06-26 11:00 UTC, KatherineCaley commented on src/cogent3/core/new_alignment.py
> +        # these methods doesn't handle reverse complement... should they?
cool! I thought so but wasn't sure

2024-06-27 02:12 UTC, GavinHuttley approved these changes
woohoo!

2024-06-27 02:12 UTC, merged