TST: port seqview tests
cogent3/cogent3 pull request #1927
Opened 2024-06-27 01:32 UTC by fredjaya

no new xfails, main changes so tests work with the new implementation are:
- adding alphabets arg to SeqView
- replacing value with str_value

nearly there...

2024-06-27 01:49 UTC, KatherineCaley commented on tests/test_core/test_sequence.py
> -@pytest.mark.parametrize("start", (None, 0, 1, 10, -1, -10))
I think we should be leaving the old tests in place

2024-06-27 02:39 UTC, GavinHuttley requested changes
leave old tests in place, just comment as # ported

2024-06-27 04:06 UTC, fredjaya commented
Will do. Should all the ones deleted up until now be re-added?

2024-06-28 05:40 UTC, fredjaya commented
Ported a few more tests and marked those in place. Let me know if I should re-add all the previous ones deleted before this PR

2024-06-29 00:21 UTC, GavinHuttley requested changes
All tests of code that remains in the original sequence, moltype, alignment and genetic_code modules, should also remain.

2024-07-02 01:33 UTC, GavinHuttley approved these changes
awesome!

2024-07-02 01:33 UTC, merged