ENH: add suuport for slicing an `IndelMap` with a step > 1
cogent3/cogent3 pull request #1991
Opened 2024-08-16 15:43 UTC by KatherineCaley

mods in this PR: 

`location.py`
- support for slicing `IndelMap` object with a positive stride, will work on negative strides now that I've worked out the logic for positive strides, partially addresses #1967

2024-08-20 01:26 UTC, GavinHuttley requested changes
Thanks for this!
Couple of suggestions, plus I suggest some integration tests, i.e. with an Aligned instance, slicing with stride matches same operation on the underlying string.

2024-08-20 08:29 UTC, KatherineCaley commented on tests/test_core/test_location.py
> +        "--AAA---C--AAAAAA",
good point!

2024-08-21 12:13 UTC, KatherineCaley commented
@GavinHuttley  I suggest that I add integration with `Aligned` in the next PR, as I have a reasonable amount of stashes changed for Aligned that I've been trying to keep separate, mainly
- implementing changes to the design of aligned/alignment as discussed on 30/07 (see board pic in zulip)
- removing the index tracking capabilities from AlignedDataView and trying to mirror the SeqsData design more closely in AlignedSeqsData

happy to push everything up now if you'd prefer 😊

2024-08-22 04:09 UTC, GavinHuttley approved these changes
Bonza bonza @KatherineCaley !

2024-08-22 04:09 UTC, merged